<?php
// Integración del CRM dentro de tests/blog.php: comparte su base desechable y servidor HTTP.
if (!isset($db, $process, $dir, $password) || !is_resource($process) || getenv('CLICOMPUTER_BLOG_TEST') !== '1') throw new RuntimeException('Ejecuta tests/blog.php para verificar el CRM.');
$db->exec('DELETE FROM blog_login_attempts');
$adminPassword = bin2hex(random_bytes(16));
$query = $db->prepare("INSERT INTO users (username, display_name, password_hash, role, created_at) VALUES ('qa_admin', 'Administración QA', ?, 'admin', UTC_TIMESTAMP())");
$query->execute([password_hash($adminPassword, PASSWORD_DEFAULT)]);
$adminId = (int) $db->lastInsertId();
$usersModel = new App\Models\AdminUser(new App\Services\BlogDatabase());
$admin = $usersModel->find($adminId);
$editorCookie = $cookie;
$cookie = $dir . '/admin-cookies.txt';
$adminCookie = $cookie;
[$status, $headers, $body] = blogHttp('/admin');
verifyBlog($status === 200 && str_contains($body, 'Entra a tu CRM'), 'CRM login missing');
verifyBlog(str_contains(strtolower($headers['set-cookie'] ?? ''), 'path=/admin'), 'CRM cookie scope incorrect');
$adminToken = blogToken($body);
verifyBlog(blogHttp('/admin/entrar', ['csrf' => $adminToken, 'username' => 'qa_admin', 'password' => $adminPassword])[0] === 303, 'Admin login failed');
[$status, $headers, $body] = blogHttp('/admin');
$adminToken = blogToken($body);
verifyBlog($status === 200 && str_contains($body, 'Vista general') && str_contains($body, '/admin/usuarios'), 'CRM dashboard missing');
verifyBlog(str_contains($headers['content-security-policy'] ?? '', "script-src 'none'") && !str_contains($body, 'analyticsConfig'), 'Private CRM scripts or analytics leak');
verifyBlog(!str_contains($body, $adminPassword) && !str_contains($body, 'password_hash'), 'Credential data leaked');
foreach (['/admin/noticias', '/admin/noticias/nueva', '/admin/usuarios', '/admin/usuarios/nuevo', '/admin/mi-cuenta'] as $route) {
    [$status, , $body] = blogHttp($route);
    verifyBlog($status === 200, 'Missing CRM screen: ' . $route);
    $document = new DOMDocument();
    $previous = libxml_use_internal_errors(true);
    $document->loadHTML($body);
    libxml_clear_errors(); libxml_use_internal_errors($previous);
    $xpath = new DOMXPath($document);
    verifyBlog($xpath->query('//h1')->length === 1, 'CRM screen lacks unique heading: ' . $route);
    foreach ($xpath->query('//link[@rel="stylesheet"]') as $link) verifyBlog(blogHttp($link->getAttribute('href'))[0] === 200, 'CRM stylesheet missing');
}
$newPassword = bin2hex(random_bytes(16));
$newUser = ['id' => '0', 'revision' => '0', 'username' => 'qa_new', 'display_name' => '<script>Equipo</script>', 'email' => 'equipo@example.com', 'role' => 'editor', 'is_active' => '1', 'password' => $newPassword, 'password_confirmation' => $newPassword, 'csrf' => $adminToken];
verifyBlog(blogHttp('/admin/usuarios/guardar', array_replace($newUser, ['csrf' => 'bad']))[0] === 403, 'User creation bypassed CSRF');
foreach ([['role' => 'owner'], ['username' => []], ['email' => 'bad'], ['display_name' => ''], ['password' => 'short'], ['password' => str_repeat('a', 73)], ['password_confirmation' => 'different'], ['is_active' => '2']] as $bad) verifyBlog(blogHttp('/admin/usuarios/guardar', array_replace($newUser, $bad))[0] === 422, 'Invalid user accepted');
verifyBlog(blogHttp('/admin/usuarios/guardar', array_replace($newUser, ['id' => 'invalid']))[0] === 400, 'Invalid ID created user');
verifyBlog(blogHttp('/admin/usuarios/guardar', $newUser)[0] === 303, 'User creation failed');
$newId = (int) $db->query("SELECT id FROM users WHERE username = 'qa_new'")->fetchColumn();
$storedHash = $db->query("SELECT password_hash FROM users WHERE id = $newId")->fetchColumn();
verifyBlog(password_verify($newPassword, $storedHash) && $storedHash !== $newPassword, 'Password not hashed');
$body = blogHttp('/admin/usuarios?q=qa_new')[2];
verifyBlog(str_contains($body, '&lt;script&gt;Equipo') && !str_contains($body, '<script>Equipo'), 'User list HTML injection');
verifyBlog(!str_contains(blogHttp('/admin/usuarios?q=none-matches')[2], 'equipo@example.com'), 'User search ignored');
verifyBlog(blogHttp('/admin/usuarios?q[]=bad')[0] === 400, 'Malformed user search accepted');
verifyBlog(blogHttp('/admin/usuarios/guardar', $newUser)[0] === 409, 'Duplicate username accepted');
$editUser = array_replace($newUser, ['id' => (string) $newId, 'revision' => '1', 'password' => '', 'password_confirmation' => '']);
verifyBlog(blogHttp('/admin/usuarios/guardar', array_replace($editUser, ['display_name' => 'Equipo de prueba']))[0] === 303, 'User edit failed');
verifyBlog(blogHttp('/admin/usuarios/guardar', $editUser)[0] === 409, 'Stale user edit accepted');
verifyBlog($db->query("SELECT password_hash FROM users WHERE id = $newId")->fetchColumn() === $storedHash, 'Empty password changed hash');
$selfInput = array_replace($newUser, ['id' => (string) $adminId, 'revision' => '1', 'username' => 'qa_admin', 'display_name' => 'Admin', 'role' => 'admin', 'password' => '', 'password_confirmation' => '']);
verifyBlog(blogHttp('/admin/usuarios/guardar', array_replace($selfInput, ['role' => 'editor']))[0] === 409, 'Admin removed own role');
verifyBlog(blogHttp('/admin/usuarios/guardar', array_replace($selfInput, ['is_active' => '0']))[0] === 409, 'Admin disabled own account');
verifyBlog(blogHttp('/admin/usuarios/guardar', array_replace($selfInput, ['password' => $newPassword, 'password_confirmation' => $newPassword]))[0] === 409, 'Self password changed without current password');
// Idempotencia: no cambia roles ni hashes al repetir la actualización.
$beforeMigration = $db->query('SELECT * FROM users ORDER BY id')->fetchAll();
App\Services\AdminSchema::migrate($db);
verifyBlog($beforeMigration === $db->query('SELECT * FROM users ORDER BY id')->fetchAll(), 'Repeated migration changed accounts');
$cookie = $editorCookie;
$editorToken = blogToken(blogHttp('/admin')[2]);
verifyBlog(blogHttp('/admin/entrar', ['csrf' => $editorToken, 'username' => 'qa_new', 'password' => $newPassword])[0] === 303, 'New user cannot log in');
$body = blogHttp('/admin')[2]; $editorToken = blogToken($body);
verifyBlog(!str_contains($body, '/admin/usuarios'), 'Editor sees user controls');
foreach (['/admin/usuarios', '/admin/usuarios/nuevo', '/admin/usuarios/editar?id=' . $adminId] as $route) verifyBlog(blogHttp($route)[0] === 403, 'Editor reads users: ' . $route);
verifyBlog(blogHttp('/admin/usuarios/guardar', array_replace($selfInput, ['csrf' => $editorToken]))[0] === 403, 'Editor escalated privilege');
verifyBlog(blogHttp('/admin/noticias/nueva')[0] === 200, 'Editor cannot access blog');
// Revocación de una sesión existente al desactivar y reactivar una cuenta.
$cookie = $adminCookie;
$editUser['revision'] = '2';
verifyBlog(blogHttp('/admin/usuarios/guardar', array_replace($editUser, ['is_active' => '0']))[0] === 303, 'Deactivation failed');
verifyBlog(str_contains(blogHttp('/admin/usuarios?estado=inactive')[2], 'qa_new'), 'Inactive filter failed');
$cookie = $editorCookie;
verifyBlog(str_contains(blogHttp('/admin/noticias')[2], 'Entrar al panel'), 'Disabled user kept session');
verifyBlog(blogHttp('/admin/noticias/guardar', $valid + ['csrf' => $editorToken, 'id' => '0', 'revision' => '0', 'status' => 'published'])[0] === 401, 'Disabled user wrote article');
$editorToken = blogToken(blogHttp('/admin')[2]);
verifyBlog(blogHttp('/admin/entrar', ['csrf' => $editorToken, 'username' => 'qa_new', 'password' => $newPassword])[0] === 401, 'Disabled user logged in');
$cookie = $adminCookie;
$editUser['revision'] = '3';
verifyBlog(blogHttp('/admin/usuarios/guardar', $editUser)[0] === 303, 'Reactivation failed');
$cookie = $editorCookie;
verifyBlog(str_contains(blogHttp('/admin/noticias')[2], 'Entrar al panel'), 'Reactivation restored stale session');
verifyBlog(blogHttp('/admin/entrar', ['csrf' => $editorToken, 'username' => 'qa_new', 'password' => $newPassword])[0] === 303, 'Reactivated login failed');
$editorToken = blogToken(blogHttp('/admin')[2]);
// Elevación y revocación: los cambios de rol exigen iniciar una nueva sesión.
$cookie = $adminCookie;
$editUser['revision'] = '4';
verifyBlog(blogHttp('/admin/usuarios/guardar', array_replace($editUser, ['role' => 'admin']))[0] === 303, 'Role change failed');
$cookie = $editorCookie;
verifyBlog(str_contains(blogHttp('/admin')[2], 'Entrar al panel'), 'Role change did not revoke session');
verifyBlog(blogHttp('/admin/entrar', ['csrf' => $editorToken, 'username' => 'qa_new', 'password' => $newPassword])[0] === 303, 'Promoted login failed');
verifyBlog(blogHttp('/admin/usuarios')[0] === 200, 'Promoted admin cannot manage users');
// Restablecimiento de contraseña desde un administrador distinto.
$cookie = $adminCookie;
$resetPassword = bin2hex(random_bytes(16));
$editUser['revision'] = '5';
verifyBlog(blogHttp('/admin/usuarios/guardar', array_replace($editUser, ['password' => $resetPassword, 'password_confirmation' => $resetPassword]))[0] === 303, 'Password reset failed');
$cookie = $editorCookie;
$editorToken = blogToken(blogHttp('/admin')[2]);
verifyBlog(str_contains(blogHttp('/admin')[2], 'Entrar al panel'), 'Reset did not revoke session');
$db->exec('DELETE FROM blog_login_attempts');
verifyBlog(blogHttp('/admin/entrar', ['csrf' => $editorToken, 'username' => 'qa_new', 'password' => $newPassword])[0] === 401, 'Old password accepted');
verifyBlog(blogHttp('/admin/entrar', ['csrf' => $editorToken, 'username' => 'qa_new', 'password' => $resetPassword])[0] === 303, 'New password rejected');
$editorToken = blogToken(blogHttp('/admin')[2]);
$ownPassword = bin2hex(random_bytes(16));
$ownInput = ['csrf' => $editorToken, 'current_password' => $resetPassword, 'password' => $ownPassword, 'password_confirmation' => $ownPassword];
verifyBlog(blogHttp('/admin/mi-cuenta', array_replace($ownInput, ['current_password' => 'bad']))[0] === 422, 'Password change without current password');
verifyBlog(blogHttp('/admin/mi-cuenta', array_replace($ownInput, ['csrf' => 'bad']))[0] === 403, 'Password change bypassed CSRF');
verifyBlog(blogHttp('/admin/mi-cuenta', $ownInput)[0] === 303, 'Self password change failed');
verifyBlog(str_contains(blogHttp('/admin')[2], 'Entrar al panel'), 'Password change kept session');
verifyBlog(blogHttp('/admin/entrar', ['csrf' => blogToken(blogHttp('/admin')[2]), 'username' => 'qa_new', 'password' => $ownPassword])[0] === 303, 'Updated password failed');
$cookie = $adminCookie;
verifyBlog(blogHttp('/admin/salir', ['csrf' => $adminToken])[0] === 303, 'CRM logout failed');
verifyBlog(str_contains(blogHttp('/admin/usuarios')[2], 'Entrar al panel'), 'Users exposed after logout');
verifyBlog(!str_contains(blogHttp('/sitemap.xml', null, false)[2], '/admin'), 'Admin indexed in sitemap');
