<section class="crm-welcome"><div><p class="crm-eyebrow">TODO EN UN MISMO LUGAR</p><h2>Hola, <?= e($adminUser['display_name'] ?: $adminUser['username']) ?>.</h2><p>Gestiona las noticias de Clicomputer y mantén tu contenido al día.</p></div><a href="/admin/noticias/nueva" class="btn btn-primary-custom"><i class="bi bi-plus-lg" aria-hidden="true"></i> Nueva noticia</a></section>
<div class="crm-stats">
  <?= $view->render('partials/admin-stat', ['statIcon' => 'globe2', 'statLabel' => 'Noticias publicadas', 'statValue' => $postCounts['published'], 'statLink' => '/admin/noticias', 'statNote' => 'Visibles en el sitio web']) ?>
  <?= $view->render('partials/admin-stat', ['statIcon' => 'file-earmark-text', 'statLabel' => 'Borradores', 'statValue' => $postCounts['draft'], 'statLink' => '/admin/noticias', 'statNote' => 'Listos para seguir editando']) ?>
  <?php if ($userCounts !== null): ?><?= $view->render('partials/admin-stat', ['statIcon' => 'people', 'statLabel' => 'Usuarios activos', 'statValue' => $userCounts['active'], 'statLink' => '/admin/usuarios', 'statNote' => $userCounts['total'] . ' cuentas en tu equipo']) ?><?php endif ?>
</div>
<div class="crm-dashboard-grid"><section class="editor-panel"><div class="crm-panel-heading"><h2>Actividad del blog</h2><a href="/admin/noticias">Ver todas <i class="bi bi-arrow-right" aria-hidden="true"></i></a></div>
  <?php if (!$recentPosts): ?><div class="crm-empty"><i class="bi bi-journal-plus" aria-hidden="true"></i><h3>Tu próxima historia empieza aquí</h3><p>Comparte novedades de tecnología o noticias de Veracruz.<br>Puedes guardar un borrador y publicarlo cuando esté listo.</p><a href="/admin/noticias/nueva" class="btn btn-outline-custom">Crear la primera noticia</a></div><?php endif ?>
  <?php foreach ($recentPosts as $post): ?><?= $view->render('partials/blog-editor-row', compact('post')) ?><?php endforeach ?>
</section><aside class="editor-panel crm-quick"><p class="crm-eyebrow">ACCESOS RÁPIDOS</p><h2>Organiza tu espacio</h2><a href="/admin/noticias/nueva"><i class="bi bi-pencil-square" aria-hidden="true"></i><span>Escribir una noticia<small>Tecnología y Veracruz</small></span><i class="bi bi-chevron-right" aria-hidden="true"></i></a><?php if ($adminUser['role'] === 'admin'): ?><a href="/admin/usuarios/nuevo"><i class="bi bi-person-plus" aria-hidden="true"></i><span>Añadir usuario<small>Define su rol y acceso</small></span><i class="bi bi-chevron-right" aria-hidden="true"></i></a><?php endif ?><a href="/noticias.html" target="_blank" rel="noopener noreferrer"><i class="bi bi-box-arrow-up-right" aria-hidden="true"></i><span>Ver el blog público<small>Así lo ven tus visitantes</small></span><i class="bi bi-chevron-right" aria-hidden="true"></i></a><p class="crm-tip"><i class="bi bi-lightbulb" aria-hidden="true"></i> Guarda como borrador para revisar el texto y la foto antes de publicar.</p></aside></div>
