<?php $self = (int) $userValues['id'] === (int) $adminUser['id']; ?>
<form class="editor-panel editor-form crm-form" method="post" action="/admin/usuarios/guardar">
<input type="hidden" name="csrf" value="<?= e($editorToken) ?>"><input type="hidden" name="id" value="<?= (int) $userValues['id'] ?>"><input type="hidden" name="revision" value="<?= (int) $userValues['revision'] ?>">
<h2 class="h5">Datos de acceso</h2><p>Los campos con * son obligatorios.</p>
<?php foreach ([['display_name', 'Nombre completo', 120, true], ['username', 'Usuario de acceso', 80, true], ['email', 'Correo de contacto', 254, false]] as [$fieldName, $label, $limit, $required]): ?>
<?= $view->render('partials/blog-editor-field', ['fieldName' => $fieldName, 'label' => $label, 'limit' => $limit, 'required' => $required, 'multiline' => false, 'help' => $fieldName === 'email' ? 'Dato de contacto del equipo. No se envían invitaciones por correo.' : '', 'editorValues' => $userValues, 'editorErrors' => $editorErrors]) ?>
<?php endforeach ?>
<div class="crm-form-columns"><div class="mb-4"><label for="userRole">Rol *</label><select class="form-select" id="userRole" name="role" required><?php foreach (App\Models\AdminUser::ROLES as $key => $label): ?><option value="<?= e($key) ?>" <?= $userValues['role'] === $key ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach ?></select><p class="form-text">Administrador: usuarios y blog. Editor: blog.</p><?php if (isset($editorErrors['role'])): ?><p class="editor-error"><?= e($editorErrors['role']) ?></p><?php endif ?></div>
<div class="mb-4"><label for="userActive">Estado *</label><select class="form-select" id="userActive" name="is_active" required><option value="1" <?= $userValues['is_active'] ? 'selected' : '' ?>>Activo</option><option value="0" <?= !$userValues['is_active'] ? 'selected' : '' ?>>Inactivo</option></select><p class="form-text">Inactivo impide el acceso y cierra sus sesiones.</p><?php if (isset($editorErrors['is_active'])): ?><p class="editor-error"><?= e($editorErrors['is_active']) ?></p><?php endif ?></div></div>
<?php if ($self): ?><p class="alert alert-info">Tu cuenta debe conservar el rol de administrador y permanecer activa. Para cambiar tu contraseña, abre <a href="/admin/mi-cuenta">Mi cuenta</a>.</p>
<?php else: ?><fieldset><legend class="h5"><?= $userValues['id'] ? 'Restablecer contraseña' : 'Contraseña inicial' ?></legend><p class="form-text"><?= $userValues['id'] ? 'Déjala vacía para conservar la actual. Cambiarla cerrará todas las sesiones de este usuario.' : 'Comunica el usuario y la contraseña directamente a la persona. Podrá cambiarla desde Mi cuenta.' ?></p>
<?php foreach (['password' => 'Contraseña', 'password_confirmation' => 'Confirmar contraseña'] as $fieldName => $label): ?><?= $view->render('partials/admin-password-field', ['fieldName' => $fieldName, 'label' => $label, 'required' => !$userValues['id'], 'editorErrors' => $editorErrors]) ?><?php endforeach ?>
</fieldset><?php endif ?>
<div class="editor-actions"><button class="btn btn-primary-custom" type="submit"><?= $userValues['id'] ? 'Guardar cambios' : 'Crear usuario' ?></button><a href="/admin/usuarios">Cancelar</a></div>
</form>
