<div class="editor-toolbar"><p class="mb-0">Gestiona quién entra al panel y qué puede administrar.</p><a class="btn btn-primary-custom" href="/admin/usuarios/nuevo"><i class="bi bi-person-plus" aria-hidden="true"></i> Nuevo usuario</a></div>
<section class="editor-panel">
<form class="crm-filters editor-form" method="get" action="/admin/usuarios"><div><label for="userSearch">Buscar usuario</label><input type="search" class="form-control" id="userSearch" name="q" value="<?= e($userSearch) ?>" maxlength="160" placeholder="Nombre, usuario o correo"></div><div><label for="userState">Estado</label><select class="form-select" id="userState" name="estado"><?php foreach (['' => 'Todos', 'active' => 'Activos', 'inactive' => 'Inactivos'] as $value => $label): ?><option value="<?= e($value) ?>" <?= $userState === $value ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach ?></select></div><button class="btn btn-outline-custom" type="submit">Filtrar</button><?php if ($userSearch !== '' || $userState !== ''): ?><a href="/admin/usuarios">Limpiar</a><?php endif ?></form>
<div class="crm-panel-heading"><h2>Equipo de Clicomputer</h2><span><?= (int) $userTotal ?> usuarios</span></div>
<?php if (!$users): ?><div class="crm-empty"><h3>No se encontraron usuarios</h3><p>Prueba con otro nombre o cambia los filtros.</p></div><?php else: ?>
<div class="crm-table-wrap" role="region" aria-label="Lista de usuarios" tabindex="0"><table class="crm-table"><thead><tr><th scope="col">Usuario</th><th scope="col">Rol</th><th scope="col">Estado</th><th scope="col"><span class="visually-hidden">Acciones</span></th></tr></thead><tbody><?php foreach ($users as $member): ?><?= $view->render('partials/admin-user-row', compact('member', 'adminUser')) ?><?php endforeach ?></tbody></table></div>
<?php endif ?>
<?php if ($userPages > 1): ?><nav class="crm-pagination" aria-label="Páginas de usuarios"><?php if ($userPage > 1): ?><a href="/admin/usuarios?<?= e(http_build_query(['q' => $userSearch, 'estado' => $userState, 'pagina' => $userPage - 1])) ?>">Anterior</a><?php endif ?><span>Página <?= $userPage ?> de <?= $userPages ?></span><?php if ($userPage < $userPages): ?><a href="/admin/usuarios?<?= e(http_build_query(['q' => $userSearch, 'estado' => $userState, 'pagina' => $userPage + 1])) ?>">Siguiente</a><?php endif ?></nav><?php endif ?>
</section>
<p class="crm-help">Los administradores gestionan usuarios y noticias. Los editores pueden escribir, editar y publicar en el blog.</p>
